services:
  app:
    container_name: telegraf-dev
    build:
      context: .
      target: deps # Використовуємо стадію, де вже є node_modules
    command: pnpm dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Щоб не перетирати модулі всередині контейнера локальними
      - /app/.next
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development