-- RLS policies for Trace (generated by audit)

-- Enable RLS
alter table public.users enable row level security;
alter table public.chats enable row level security;
alter table public.messages enable row level security;
-- NOTE: storage.objects is owned by supabase_admin in hosted Supabase.
-- Enabling RLS here can fail with "must be owner of table objects".
-- If needed, enable RLS for storage.objects via Supabase SQL Editor as postgres/supabase_admin.

-- USERS
drop policy if exists "Users can view own profile" on public.users;
create policy "Users can view own profile"
  on public.users for select
  using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.users;
create policy "Users can update own profile"
  on public.users for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.users;
create policy "Users can insert own profile"
  on public.users for insert
  with check (auth.uid() = id);

-- CHATS
drop policy if exists "Users can view own chats" on public.chats;
create policy "Users can view own chats"
  on public.chats for select
  using (auth.uid() = user_id or auth.uid() = recipient_id);

drop policy if exists "Users can create chats" on public.chats;
create policy "Users can create chats"
  on public.chats for insert
  with check (
    auth.uid() = user_id
    and user_id <> recipient_id
    and recipient_id in (select id from public.users)
  );

drop policy if exists "Users can update own chats" on public.chats;
create policy "Users can update own chats"
  on public.chats for update
  using (auth.uid() = user_id or auth.uid() = recipient_id)
  with check (auth.uid() = user_id or auth.uid() = recipient_id);

drop policy if exists "Users can delete own chats" on public.chats;
create policy "Users can delete own chats"
  on public.chats for delete
  using (auth.uid() = user_id or auth.uid() = recipient_id);

-- MESSAGES
drop policy if exists "Users can view chat messages" on public.messages;
create policy "Users can view chat messages"
  on public.messages for select
  using (
    chat_id in (
      select id from public.chats
      where user_id = auth.uid() or recipient_id = auth.uid()
    )
  );

drop policy if exists "Users can send messages" on public.messages;
create policy "Users can send messages"
  on public.messages for insert
  with check (
    auth.uid() = sender_id
    and chat_id in (
      select id from public.chats
      where user_id = auth.uid() or recipient_id = auth.uid()
    )
  );

drop policy if exists "Users can edit own messages" on public.messages;
create policy "Users can edit own messages"
  on public.messages for update
  using (auth.uid() = sender_id)
  with check (auth.uid() = sender_id);

drop policy if exists "Users can delete own messages" on public.messages;
create policy "Users can delete own messages"
  on public.messages for delete
  using (auth.uid() = sender_id);

-- STORAGE (attachments bucket)
-- Path format: chatId/userId/filename
-- storage.foldername(name)[1] = chatId, [2] = userId

drop policy if exists "Users can upload attachments" on storage.objects;
create policy "Users can upload attachments"
  on storage.objects for insert
  with check (
    bucket_id = 'attachments'
    and (storage.foldername(name))[2] = auth.uid()::text
    and (storage.foldername(name))[1]::uuid in (
      select id from public.chats
      where user_id = auth.uid() or recipient_id = auth.uid()
    )
  );

drop policy if exists "Users can view chat attachments" on storage.objects;
create policy "Users can view chat attachments"
  on storage.objects for select
  using (
    bucket_id = 'attachments'
    and (storage.foldername(name))[1]::uuid in (
      select id from public.chats
      where user_id = auth.uid() or recipient_id = auth.uid()
    )
  );

drop policy if exists "Users can delete own attachments" on storage.objects;
create policy "Users can delete own attachments"
  on storage.objects for delete
  using (
    bucket_id = 'attachments'
    and (storage.foldername(name))[2] = auth.uid()::text
  );

drop policy if exists "Users can update own attachments" on storage.objects;
create policy "Users can update own attachments"
  on storage.objects for update
  using (
    bucket_id = 'attachments'
    and (storage.foldername(name))[2] = auth.uid()::text
  )
  with check (
    bucket_id = 'attachments'
    and (storage.foldername(name))[2] = auth.uid()::text
  );
